### ISSUE TITLE
Datasets deploy is failed due to Firecache is enabled by default

### ISSUE THREAD

**Issue by sgrebnov** [spiceai/spice-app-template#3]
Repro steps:
1. Create Spice account
2. Create new app
3. `Datasets` -> Link repo
4. Create new repo from `spice-app-template`
5. Click `Deploy`

`500 Failed to publish dataset`

Manually updating `firecache.enabled` to `false` fixes the problem. 

Firecache is the Enterprise plan. Should quick start template has it disabled by default?

**Comment by ewgenius** [comment]
Thank you for noticing, @sgrebnov!
